## NumPy:
Une bibliothèque qui fournit les bases de calcul scientifique

Elle offre toutes les fonctionnalités essentielles et introduit deux types fondamentaux:
               Les tableaux et matrices.


### Tableaux multidimensionnels
La fonctionnalité de base de NumPy est ndarray, qui représente un tableau multidimensionnel

In [ ]:
pip install numpy

In [ ]:
import numpy as np #où np est l'alias qu'on avait donné à la bibliothèque numpy

Pour en déclarer un, il suffit de créer une liste Python de base et d’utiliser le constructeur "np.array"

In [ ]:
np.array( [1,2,3,5,6,7,8])

array([1, 2, 3, 5, 6, 7, 8])

In [ ]:
Pour créer plusieurs dimensions, il suffit de créer des listes de liste

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

La manière dont les listes sont arrangées définit la dimension du tableau :

In [ ]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]]) #créer un tableau nommé arr
arr.shape

(3, 3)

In [ ]:
arr= np.array([[1,2],[3,4],[5,6],[7,8]]) #créer un tableau nommé arr
arr.shape

(4, 2)

In [ ]:
arr= np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10],[11,12]]]) #créer un tableau nommé arr
print(arr.shape)
arr


(3, 2, 2)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

On dispose d’une fonctionnalité qui permet de produire des nombres à la manières du générateur range de Python (min,max, step)

In [ ]:
np.arange(1,9) # min =1, max=9

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2,7,2)

array([2, 4, 6])

On peut également gérer les dimensions dans un second temps

In [ ]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

L’ordre des dimensions est important

In [ ]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Et voici arriver le tableau à trois dimensions

In [ ]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Enfin, on peut aussi remettre un tableau à plat très facilement pour obtenir un tableau à une dimension

In [ ]:
arr=np.arange(1,9).reshape(2,2,2)
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

#### Quelques fonctions prédéfinies

Admettons maintenant que nous avons que nous soyons face à un tableau multidimensionnel et que nous souhaitons récupérer des informations

In [ ]:
a=np.arange(100).reshape(5,5,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

Pour obtenir le nombre de dimensions:

In [ ]:
a.ndim

3

Quelle est la taille de chaque dimension

In [ ]:
a.shape


(5, 5, 4)

Le nombre d’élèments dans le tableau

In [ ]:
a.size

100

Le nom du type de données des objets présents dans le tableau

In [ ]:
a.dtype.name

'int64'

Créer des tableaux en les remplissant de 0  et 1

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Opérateurs crochets

NumPy permet de gérer les dimensions en utilisant l’opérateur crochet.

In [ ]:
ar=np.arange(1,9).reshape(4,2)
ar

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
ar[0,0] #récupérer la valeur du premier élèment

1

In [ ]:
ar[-1,-1] #récupérer la valeur du dernier élèment

8

In [ ]:
ar[1,-1]#récupérer le dernier élèment de la seconde ligne

4

Itérer indépendamment de la structure du tableau

In [ ]:
for elt in ar.flat:
    print(elt)

1
2
3
4
5
6
7
8


#### Opérateurs basiques


In [ ]:
Les algorithmes usuels de Python fonctionnent toujours avec  les objets NumPy:

In [ ]:
a=np.array([5,6,4,3,2,7])
3 in a #vérifier si 3 est un élèment du tableau a

True

Plusieurs opérations sont offertes pour manipuler le contenu des tableaux:


In [ ]:
a=np.array([5,6,4,3,2,7]).reshape(3,2)
print(a)
print('somme=', a.sum(axis=0)) #somme des élèments d'une colonne
print('min=', a.min(axis=1)) #mininum par ligne
print('max=', a.max(axis=0)) #maximum par colonne

[[5 6]
 [4 3]
 [2 7]]
somme= [11 16]
min= [5 3 2]
max= [5 7]


Il est possible d'effectuer un produit entre tous les éléments d'un tableau

In [ ]:
a= np.arange(2,9,2)
b= np.arange(20,5,-4)
print(a)
print(b)
print(np.dot(a,b))

[2 4 6 8]
[20 16 12  8]
240


Il faut pas confondre avec la multiplication (qui multiplie entre eux chaque nombre aux mêmes positions)

In [ ]:
a*b

array([40, 64, 72, 64])

Il est possible d'effectuer toute sorte d'opération

In [ ]:
c= np.arange(6,15)
print(c)
print(c-5)
print(c/2)
print(c*0.5)
print(np.sqrt(c))#racine carrée de tous les élèments

[ 6  7  8  9 10 11 12 13 14]
[1 2 3 4 5 6 7 8 9]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7. ]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7. ]
[2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


Concaténer verticalement ou horizontalement deux tableaux

In [ ]:
np.hstack((a,b))

array([ 2,  4,  6,  8, 20, 16, 12,  8])

In [ ]:
np.vstack((a,b))

array([[ 2,  4,  6,  8],
       [20, 16, 12,  8]])

### Matrices

Trois exemples pour déclarer la même matrice

In [ ]:
np.matrix([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [ ]:
np.matrix(np.arange(1,5).reshape(2,2))

matrix([[1, 2],
        [3, 4]])

In [ ]:
np.matrix('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

Les matrices peuvent s'additionner ou se soustraire

In [ ]:
np.matrix('1 2; 3 4') + np.matrix('8 7; 6 5')

matrix([[9, 9],
        [9, 9]])

In [ ]:
np.matrix('1 2; 3 4') - np.matrix('8 7; 6 5')

matrix([[-7, -5],
        [-3, -1]])

In [ ]:
#La transposée
c=np.matrix('1 2; 3 4')
c.T

matrix([[1, 3],
        [2, 4]])